<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="CompareNETObjects" Version="4.83.0" />
      <PackageReference Include="DotNetCore.CAP" Version="10.0.1" />
      <PackageReference Include="DotNetCore.CAP.Dashboard" Version="10.0.1" />
      <PackageReference Include="DotNetCore.CAP.SqlServer" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.8" />
      <PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="10.0.0" />
  </ItemGroup>
	
	<ItemGroup>
    <ProjectReference Include="..\shared\Napoleon.Shared.Core\Napoleon.Shared.Core.csproj" />
    <ProjectReference Include="..\shared\Napoleon.Shared.Infrastructure\Napoleon.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Napoleon.Fos.Contract\Napoleon.Fos.Contract.csproj" />
    <ProjectReference Include="..\Napoleon.Fos.Core\Napoleon.Fos.Core.csproj" />
  </ItemGroup>

</Project>
